version: '3.8'

services:
  db1:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: balance
      POSTGRES_USER: balance
      POSTGRES_PASSWORD: balance
    ports:
      - "5432:5432"
    volumes:
      - db_shop_data:/var/lib/postgresql/data


volumes:
  db_shop_data: